name: use-vanity-dev-engine

on:
  pull_request:
    branches: ["**"]
  push:
    branches: [main, develop, "release/**", "fix/**", "feature/**"]

jobs:
  use-vanity-dev-engine:
    if: ${{ vars.USE_VANITY_DEV_ENGINE == 'true' }}
    uses: OliverGiertz/vanity-dev-engine/.github/workflows/repo-pipeline.yml@431a1d254324ef2ecfa0262c2cd1b544e3aafd29 # v1.5
    with:
      repo_type: ios
